import localFont from "next/font/local";
import { Header } from "@/components/header/header";
import { Footer } from "@/components/footer/footer";
import { Providers } from "./providers";
import "@/theme/globals.scss";

const fontRvoucherSansRegular = localFont({
  src: "../theme/fonts/RvoucherSans-Regular.woff",
  variable: "--rvoucher-sans-regular",
});

const fontRvoucherSansMedium = localFont({
  src: "../theme/fonts/RvoucherSans-Medium.woff",
  variable: "--rvoucher-sans-medium",
});

const fontRvoucherSansBold = localFont({
  src: "../theme/fonts/RvoucherSans-Bold.woff",
  variable: "--rvoucher-sans-bold",
});

export const metadata = {
  title: "Red Voucher Online",
  description: "Generated by rvol",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="es"
      className={`${fontRvoucherSansRegular.variable} ${fontRvoucherSansMedium.variable} ${fontRvoucherSansBold.variable} antialiased`}
    >
      <head>
        <meta
          name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
        />
      </head>
      <body>
        <Providers>
          <Header />
          <main className="main">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
